Revert "Merge branch 'master' into testing"
This reverts commit 29ee916f437c89f15e1995d2f306bbe17038ba85, reversing
changes made to 2d131e1fd99483b4eebe019cf7e75c1de3fa4194.

diff --git a/tools/testing/selftests/ftrace/ftracetest b/tools/testing/selftests/ftrace/ftracetest
--- a/tools/testing/selftests/ftrace/ftracetest
+++ b/tools/testing/selftests/ftrace/ftracetest
@@ -8,18 +8,13 @@
 # Released under the terms of the GPL v2.
 
 usage() { # errno [message]
-[ ! -z "$2" ] && echo $2
+[ "$2" ] && echo $2
 echo "Usage: ftracetest [options] [testcase(s)] [testcase-directory(s)]"
 echo " Options:"
 echo "		-h|--help  Show help message"
 echo "		-k|--keep  Keep passed test logs"
-echo "		-v|--verbose Increase verbosity of test messages"
-echo "		-vv        Alias of -v -v (Show all results in stdout)"
-echo "		-vvv       Alias of -v -v -v (Show all commands immediately)"
-echo "		--fail-unsupported Treat UNSUPPORTED as a failure"
+echo "		-v|--verbose Show all stdout messages in testcases"
 echo "		-d|--debug Debug mode (trace all shell commands)"
-echo "		-l|--logdir <dir> Save logs on the <dir>"
-echo "		            If <dir> is -, all logs output in console only"
 exit $1
 }
 
@@ -50,7 +45,7 @@ parse_opts() { # opts
   local OPT_TEST_CASES=
   local OPT_TEST_DIR=
 
-  while [ ! -z "$1" ]; do
+  while [ "$1" ]; do
     case "$1" in
     --help|-h)
       usage 0
@@ -59,23 +54,13 @@ parse_opts() { # opts
       KEEP_LOG=1
       shift 1
     ;;
-    --verbose|-v|-vv|-vvv)
-      VERBOSE=$((VERBOSE + 1))
-      [ $1 = '-vv' ] && VERBOSE=$((VERBOSE + 1))
-      [ $1 = '-vvv' ] && VERBOSE=$((VERBOSE + 2))
+    --verbose|-v)
+      VERBOSE=1
       shift 1
     ;;
     --debug|-d)
       DEBUG=1
       shift 1
-    ;;
-    --fail-unsupported)
-      UNSUPPORTED_RESULT=1
-      shift 1
-    ;;
-    --logdir|-l)
-      LOG_DIR=$2
-      shift 2
     ;;
     *.tc)
       if [ -f "$1" ]; then
@@ -96,19 +81,14 @@ parse_opts() { # opts
     ;;
     esac
   done
-  if [ ! -z "$OPT_TEST_CASES" ]; then
+  if [ "$OPT_TEST_CASES" ]; then
     TEST_CASES=$OPT_TEST_CASES
   fi
 }
 
 # Parameters
 DEBUGFS_DIR=`grep debugfs /proc/mounts | cut -f2 -d' ' | head -1`
-if [ -z "$DEBUGFS_DIR" ]; then
-    TRACING_DIR=`grep tracefs /proc/mounts | cut -f2 -d' ' | head -1`
-else
-    TRACING_DIR=$DEBUGFS_DIR/tracing
-fi
-
+TRACING_DIR=$DEBUGFS_DIR/tracing
 TOP_DIR=`absdir $0`
 TEST_DIR=$TOP_DIR/test.d
 TEST_CASES=`find_testcases $TEST_DIR`
@@ -116,32 +96,25 @@ LOG_DIR=$TOP_DIR/logs/`date +%Y%m%d-%H%M%S`/
 KEEP_LOG=0
 DEBUG=0
 VERBOSE=0
-UNSUPPORTED_RESULT=0
 # Parse command-line options
 parse_opts $*
 
 [ $DEBUG -ne 0 ] && set -x
 
 # Verify parameters
-if [ -z "$TRACING_DIR" -o ! -d "$TRACING_DIR" ]; then
+if [ -z "$DEBUGFS_DIR" -o ! -d "$TRACING_DIR" ]; then
   errexit "No ftrace directory found"
 fi
 
 # Preparing logs
-if [ "x$LOG_DIR" = "x-" ]; then
-  LOG_FILE=
-  date
-else
-  LOG_FILE=$LOG_DIR/ftracetest.log
-  mkdir -p $LOG_DIR || errexit "Failed to make a log directory: $LOG_DIR"
-  date > $LOG_FILE
-fi
-
+LOG_FILE=$LOG_DIR/ftracetest.log
+mkdir -p $LOG_DIR || errexit "Failed to make a log directory: $LOG_DIR"
+date > $LOG_FILE
 prlog() { # messages
-  [ -z "$LOG_FILE" ] && echo "$@" || echo "$@" | tee -a $LOG_FILE
+  echo "$@" | tee -a $LOG_FILE
 }
 catlog() { #file
-  [ -z "$LOG_FILE" ] && cat $1 || cat $1 | tee -a $LOG_FILE
+  cat $1 | tee -a $LOG_FILE
 }
 prlog "=== Ftrace unit tests ==="
 
@@ -165,16 +138,11 @@ XFAILED_CASES=
 UNDEFINED_CASES=
 TOTAL_RESULT=0
 
-INSTANCE=
 CASENO=0
 testcase() { # testfile
   CASENO=$((CASENO+1))
   desc=`grep "^#[ \t]*description:" $1 | cut -f2 -d:`
-  prlog -n "[$CASENO]$INSTANCE$desc"
-}
-
-test_on_instance() { # testfile
-  grep -q "^#[ \t]*flags:.*instance" $1
+  prlog -n "[$CASENO]$desc"
 }
 
 eval_result() { # sigval
@@ -202,7 +170,7 @@ eval_result() { # sigval
     $UNSUPPORTED)
       prlog "	[UNSUPPORTED]"
       UNSUPPORTED_CASES="$UNSUPPORTED_CASES $CASENO"
-      return $UNSUPPORTED_RESULT # depends on use case
+      return 1 # this is not a bug, but the result should be reported.
     ;;
     $XFAIL)
       prlog "	[XFAIL]"
@@ -222,14 +190,7 @@ SIG_RESULT=
 SIG_BASE=36	# Use realtime signals
 SIG_PID=$$
 
-exit_pass () {
-  exit 0
-}
-
 SIG_FAIL=$((SIG_BASE + FAIL))
-exit_fail () {
-  exit 1
-}
 trap 'SIG_RESULT=$FAIL' $SIG_FAIL
 
 SIG_UNRESOLVED=$((SIG_BASE + UNRESOLVED))
@@ -262,27 +223,18 @@ trap 'SIG_RESULT=$XFAIL' $SIG_XFAIL
 
 __run_test() { # testfile
   # setup PID and PPID, $$ is not updated.
-  (cd $TRACING_DIR; read PID _ < /proc/self/stat; set -e; set -x; initialize_ftrace; . $1)
+  (cd $TRACING_DIR; read PID _ < /proc/self/stat ; set -e; set -x; . $1)
   [ $? -ne 0 ] && kill -s $SIG_FAIL $SIG_PID
 }
 
 # Run one test case
 run_test() { # testfile
   local testname=`basename $1`
-  if [ ! -z "$LOG_FILE" ] ; then
-    local testlog=`mktemp $LOG_DIR/${testname}-log.XXXXXX`
-  else
-    local testlog=/proc/self/fd/1
-  fi
-  export TMPDIR=`mktemp -d /tmp/ftracetest-dir.XXXXXX`
+  local testlog=`mktemp $LOG_DIR/${testname}-log.XXXXXX`
   testcase $1
-  echo "execute$INSTANCE: "$1 > $testlog
+  echo "execute: "$1 > $testlog
   SIG_RESULT=0
-  if [ -z "$LOG_FILE" ]; then
-    __run_test $1 2>&1
-  elif [ $VERBOSE -ge 3 ]; then
-    __run_test $1 | tee -a $testlog 2>&1
-  elif [ $VERBOSE -eq 2 ]; then
+  if [ $VERBOSE -ne 0 ]; then
     __run_test $1 2>> $testlog | tee -a $testlog
   else
     __run_test $1 >> $testlog 2>&1
@@ -290,12 +242,11 @@ run_test() { # testfile
   eval_result $SIG_RESULT
   if [ $? -eq 0 ]; then
     # Remove test log if the test was done as it was expected.
-    [ $KEEP_LOG -eq 0 -a ! -z "$LOG_FILE" ] && rm $testlog
+    [ $KEEP_LOG -eq 0 ] && rm $testlog
   else
-    [ $VERBOSE -eq 1 -o $VERBOSE -eq 2 ] && catlog $testlog
+    catlog $testlog
     TOTAL_RESULT=1
   fi
-  rm -rf $TMPDIR
 }
 
 # load in the helper functions
@@ -304,17 +255,6 @@ run_test() { # testfile
 # Main loop
 for t in $TEST_CASES; do
   run_test $t
-done
-
-# Test on instance loop
-INSTANCE=" (instance) "
-for t in $TEST_CASES; do
-  test_on_instance $t || continue
-  SAVED_TRACING_DIR=$TRACING_DIR
-  export TRACING_DIR=`mktemp -d $TRACING_DIR/instances/ftracetest.XXXXXX`
-  run_test $t
-  rmdir $TRACING_DIR
-  TRACING_DIR=$SAVED_TRACING_DIR
 done
 
 prlog ""
